{
 "title": "Walrus Storage Node",
 "description": "This dashboard provides key insights into the performance and health of Storage Operators within the Walrus decentralized storage network. Storage Operators are the backbone of the system, responsible for storing and serving data slivers that collectively form the decentralized storage layer.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the Walrus Storage Node.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_build_info{service=\"storage_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the Walrus network.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{service=\"storage_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Displays the total uptime of the Walrus Storage Node in days, indicating its operational status.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Displays the current status of the Walrus storage node.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "data.nodeStatus", "text": "Status", "type": "string" }
     ],
     "json_options": {
      "columnar": false,
      "root_is_not_array": true
     },
     "root_selector": "$.*",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "Displays the current epoch number in the Walrus network, indicating the network's operational state.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_current_epoch{service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Epoch State Timeline",
   "type": "timeseries",
   "description": "Displays the timeline of Walrus Storage Node epoch states, highlighting transitions between inactive (0) and active (1) statuses.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_current_epoch_state{service=\"storage_node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "timeseries",
   "description": "Displays the uptime trend status of the Walrus Storage Node. Green indicates uptime is increasing, and red indicates it is not.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(uptime{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Address",
   "type": "stat",
   "description": "Displays the current SUI address used by the Walrus Storage Node.",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_sui_balance_mist{service=\"storage_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sui Balance Over Time",
   "type": "timeseries",
   "description": "Shows the historical Sui token balance of the Walrus storage node.",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "walrus_sui_balance_mist{service=\"storage_node\"} / 1e9",
     "legendFormat": "SUI Balance"
    }
   ]
  },
  {
   "title": "Sui Balance",
   "type": "stat",
   "description": "Displays the current SUI token balance (in SUI) for the storage node in the Walrus network.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_sui_balance_mist{service=\"storage_node\"}) / 1e9"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Checkpoint Lag",
   "type": "stat",
   "description": "Displays the current checkpoint lag between the local store and the full node in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(checkpoint_downloader_checkpoint_lag{service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "stat",
   "description": "Displays the number of active workers in the checkpoint downloader's worker pool for the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkpoint_downloader_num_workers{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Total Downloaded Checkpoints",
   "type": "stat",
   "description": "Displays the total number of checkpoints downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_processor_total_downloaded_checkpoints{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Latest Downloaded Checkpoint",
   "type": "stat",
   "description": "Displays the latest full checkpoint downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_processor_latest_downloaded_checkpoint{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Checkpoint Lag Over Time",
   "type": "timeseries",
   "description": "Displays the maximum checkpoint lag over time in the Walrus network, helping to identify delays between local store and full node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(checkpoint_downloader_checkpoint_lag{service=\"storage_node\"})",
     "legendFormat": "Latest Lag"
    }
   ]
  },
  {
   "title": "Checkpoint Download Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the latest full checkpoint downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_event_processor_latest_downloaded_checkpoint{service=\"storage_node\"}",
     "legendFormat": "Latest Checkpoint"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pending Events",
   "type": "stat",
   "description": "Displays the number of Walrus events currently in the pending state.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"pending\", service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Persisted Events",
   "type": "stat",
   "description": "Displays the number of Walrus events currently in the persisted state.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"persisted\", service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Average Event Processing Time",
   "type": "timeseries",
   "description": "Displays the average processing time for each event type in the Walrus network, with color thresholds for performance monitoring.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(walrus_event_process_duration_seconds_sum{service=\"storage_node\"}[$__rate_interval])) / sum by (event_type) (rate(walrus_event_process_duration_seconds_count{service=\"storage_node\"}[$__rate_interval]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Persisted Event Cursor Progress",
   "type": "timeseries",
   "description": "Displays the progress of persisted events in the Walrus network over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"persisted\", service=\"storage_node\"}",
     "legendFormat": "Persisted Events"
    }
   ]
  },
  { "title": "Span Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Latency Distribution",
   "type": "timeseries",
   "description": "Displays the latency distribution for spans in the storage node service, categorized by span names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tracing_span_latencies_bucket{service=\"storage_node\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "95th percentile - {{span_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Displays the average latency for spans in the storage node service.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "tracing_span_latencies_sum{service=\"storage_node\"} / tracing_span_latencies_count{service=\"storage_node\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Summary",
   "type": "stat",
   "description": "Displays a summary of owned and read-only shard statuses.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "data.shardSummary.owned", "text": "Owned", "type": "number" },
      { "selector": "data.shardSummary.readOnly", "text": "Read Only", "type": "number" }
     ],
     "json_options": {
      "columnar": false,
      "root_is_not_array": true
     },
     "root_selector": "$.*",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Shard Status",
   "type": "stat",
   "description": "Displays the statuses of owned shards.",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      {
       "selector": "data.shardSummary.ownedShardStatus.unknown",
       "text": "Unknown",
       "type": "number"
      },
      {
       "selector": "data.shardSummary.ownedShardStatus.ready",
       "text": "Ready",
       "type": "number"
      },
      {
       "selector": "data.shardSummary.ownedShardStatus.inTransfer",
       "text": "In Transfer",
       "type": "number"
      },
      {
       "selector": "data.shardSummary.ownedShardStatus.inRecovery",
       "text": "In Recovery",
       "type": "number"
      }
     ],
     "json_options": {
      "columnar": false,
      "root_is_not_array": true
     },
     "root_selector": "$.*",
     "source": "url",
     "type": "json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Total Metadata Blob Size Processed",
   "type": "stat",
   "description": "Displays the total unencoded size of all uploaded blobs based on metadata.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_uploaded_metadata_unencoded_blob_bytes_sum{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Total Storage Confirmations",
   "type": "stat",
   "description": "Displays the total number of storage confirmations issued.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_storage_confirmations_issued_total{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Total Metadata Operations",
   "type": "stat",
   "description": "Displays the total count of metadata operations (stored and retrieved) in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_metadata_stored_total + walrus_metadata_retrieved_total{service=\"storage_node\"}",
     "legendFormat": "Total Metadata Operations"
    }
   ]
  },
  {
   "title": "Total Sliver Operations",
   "type": "stat",
   "description": "Displays the total count of sliver operations (retrieved and stored) across all types (primary and secondary).",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_slivers_retrieved_total{sliver_type=\"primary\", service=\"storage_node\"} + walrus_slivers_stored_total{sliver_type=\"primary\", service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Sliver Operations Rate",
   "type": "timeseries",
   "description": "Displays the rate of sliver operations (retrieved and stored) over time, separated by type (primary or secondary).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_slivers_retrieved_total{sliver_type=\"primary\", service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Retrieved - Primary"
    },
    {
     "expr": "rate(walrus_slivers_retrieved_total{sliver_type=\"secondary\", service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Retrieved - Secondary"
    },
    {
     "expr": "rate(walrus_slivers_stored_total{sliver_type=\"primary\", service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Stored - Primary"
    },
    {
     "expr": "rate(walrus_slivers_stored_total{sliver_type=\"secondary\", service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Stored - Secondary"
    }
   ]
  },
  {
   "title": "Rates of Metadata Operations",
   "type": "timeseries",
   "description": "Displays the rate of metadata operations (stored and retrieved) over time, enabling a comparison of storage and retrieval rates.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_metadata_stored_total{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Metadata Stored Rate"
    },
    {
     "expr": "rate(walrus_metadata_retrieved_total{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Metadata Retrieval Rate"
    }
   ]
  },
  {
   "title": "Rate of Storage Confirmations Issued",
   "type": "timeseries",
   "description": "Displays the rate at which storage confirmations are issued over time in the Walrus network.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_storage_confirmations_issued_total{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Confirmations"
    }
   ]
  },
  { "title": "Recovery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Blob Recovery In-Progress",
   "type": "stat",
   "description": "Displays the current number of blob recoveries that are in-progress on the node in the Walrus network.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_recover_blob_backlog{state=\"in-progress\", service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Blob Recovery Queued",
   "type": "stat",
   "description": "Displays the current number of blob recoveries queued by the node in the Walrus network.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_recover_blob_backlog{state=\"queued\", service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Blob Recovery Backlog Timeline",
   "type": "timeseries",
   "description": "Displays the timeline of blob recovery backlog states in the Walrus network, highlighting transitions between 'in-progress' and 'queued' statuses.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_recover_blob_backlog{state=~\"in-progress|queued\", service=\"storage_node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Blob Recovery Duration",
   "type": "timeseries",
   "description": "Displays the time (in seconds) spent recovering blobs in the Walrus network, categorized by skip and success statuses.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(walrus_recover_blob_duration_seconds_bucket{service=\"storage_node\"}[$__rate_interval])) by (le, status))",
     "legendFormat": "95th percentile - {{status}}"
    },
    {
     "expr": "sum(rate(walrus_recover_blob_duration_seconds_sum{service=\"storage_node\"}[$__rate_interval])) by (status) / sum(rate(walrus_recover_blob_duration_seconds_count{service=\"storage_node\"}[$__rate_interval])) by (status)",
     "legendFormat": "Average - {{status}}"
    }
   ]
  },
  {
   "title": "Blob Part Recovery Duration",
   "type": "timeseries",
   "description": "Displays the time spent recovering blob parts (metadata, primary, secondary) in the Walrus network, categorized by status (success, skip).",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(walrus_recover_blob_part_duration_seconds_bucket{service=\"storage_node\"}[$__rate_interval])) by (le, part, status))",
     "legendFormat": "95th Percentile - {{part}} - {{status}}"
    },
    {
     "expr": "sum(rate(walrus_recover_blob_part_duration_seconds_sum{service=\"storage_node\"}[$__rate_interval])) by (part, status) / sum(rate(walrus_recover_blob_part_duration_seconds_count{service=\"storage_node\"}[$__rate_interval])) by (part, status)",
     "legendFormat": "Average - {{part}} - {{status}}"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Block Cache Hit Rate Over Time",
   "type": "timeseries",
   "description": "Shows the block cache hit rate for each column family in the Walrus Storage Node over time, helping identify trends and patterns in cache usage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "targets": [
    {
     "expr": "rate(block_cache_hit_count{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Block Read Rate Over Time",
   "type": "timeseries",
   "description": "Shows the block read rate for each column family in the Walrus Storage Node, indicating the volume of data being read from the file system over time. Useful for analyzing potential bottlenecks caused by large blocks or queries.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(block_read_byte{service=\"storage_node\"}[$__rate_interval]) / (1024 * 1024)",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Get Read Bytes Over Time",
   "type": "timeseries",
   "description": "Shows the total bytes read for values returned by Get operations in the Walrus Storage Node over time. This metric highlights read activity by column family.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(get_read_bytes{service=\"storage_node\"}[$__rate_interval]) / (1024 * 1024)",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Block Read Count Over Time",
   "type": "timeseries",
   "description": "Shows the block read count for each column family in the Walrus Storage Node over time. This metric highlights instances of direct file system reads, indicating potential cache misses or scenarios where the block cache is disabled.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(block_read_count{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "HTTP Request Duration Over Time",
   "type": "timeseries",
   "description": "Displays the duration of HTTP requests for different routes and their status codes in the Walrus Storage Node over time. The right column in the legend shows the HTTP method, route (Name), and status code (Status).",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"storage_node\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{service=\"storage_node\"}[$__rate_interval])",
     "legendFormat": "Name: {{method}} {{route}} {{status_code}}"
    }
   ]
  }
 ]
}